language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

env:
  - "BUNDLE_GEMFILE=warden-client/Gemfile"
  - "BUNDLE_GEMFILE=warden-protocol/Gemfile"

script:
  - if [ $BUNDLE_GEMFILE == 'warden-client/Gemfile' ]; then bundle exec rspec warden-client/spec; fi
  - if [ $BUNDLE_GEMFILE == 'warden-protocol/Gemfile' ]; then bundle exec rspec warden-protocol/spec; fi
